#!/usr/bin/env python3
"""Convert generated js-ephemeris-lite asteroid constants to Dart."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def extract(path: Path, name: str) -> str:
    source = path.read_text(encoding="ascii")
    match = re.search(rf"export const {name} = '([^']+)';", source)
    if not match:
        raise ValueError(f"{name} not found in {path}")
    return match.group(1)


def dart_string(value: str, width: int = 100) -> str:
    chunks = [value[i : i + width] for i in range(0, len(value), width)]
    return "\n".join(f"    '{chunk}'" for chunk in chunks) + ";\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("js_package", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    stable = extract(args.js_package / "src/asteroid-stable-data.js", "STABLE_ASTEROID_DATA_BASE64")
    centaur_source = (args.js_package / "src/asteroid-centaur-data.js").read_text(encoding="ascii")
    centaur = extract(args.js_package / "src/asteroid-centaur-data.js", "CENTAUR_ASTEROID_DATA_BASE64")
    counts_match = re.search(r"Object\.freeze\(\[([^]]+)\]\)", centaur_source)
    if not counts_match:
        raise ValueError("centaur counts not found")
    counts = ", ".join(part.strip() for part in counts_match.group(1).split(","))
    output = (
        "// Generated by tool/port_js_data.py; do not edit.\n"
        f"const centaurAsteroidCounts = <int>[{counts}];\n"
        "const stableAsteroidDataBase64 =\n"
        + dart_string(stable)
        + "const centaurAsteroidDataBase64 =\n"
        + dart_string(centaur)
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="ascii")


if __name__ == "__main__":
    main()
